version: "3"
services:
  apache:
    build:
      context: .
    ports:
    - "8080:80"
    volumes:
    - .:/var/www/html
  db:
    image: "mariadb:10.5.5"
    ports:
      - "3333:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=iot-chns

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    environment:
      - PMA_HOST=db

